n = int(input('Luiz Carlos Goulart Inacio Lula Da Silva Gomes Coutinho Queiroz Digite um Numero'))
num = str(n)
print('numero {}'.format(num[3]))
print('numero {}'.format(num[2]))
print('numero {}'.format(num[1]))
print('numero {}'.format(num[0]))